baseurl = "your-site-address"
title = "your-site-name"
languageCode = "ko-KR"

theme = "hello-programmer"

paginate = 2

disqusShortname = "XXXX"
googleAnalytics = "UA-XXXXXXXX-X"

[author]
    name = "your-name"
    email = "your-email"
